# Generated by Django 4.2.1 on 2023-05-06 04:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reply_success', models.BooleanField(default=0)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_contact', to='contact.contact')),
            ],
        ),
    ]
