name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Config SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: App Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ~/projects/portfolio/portfolio_backend && git pull origin main && source env/bin/activate && pip install -r requirements.txt && python manage.py makemigrations contact && python manage.py migrate && systemctl restart portfolio"
